# Generated by Django 4.2.7 on 2025-12-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_hospitaliere", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
        ),
    ]
