# Generated by Django 4.2.7 on 2025-12-15 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_hospitaliere", "0002_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="date_embauche",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="salaire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="statut_de_connexion",
            field=models.CharField(
                choices=[("actif", "Actif"), ("inactif", "Inactif")],
                default="inactif",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="poste",
            field=models.CharField(
                choices=[
                    ("receptioniste", "Receptioniste"),
                    ("caissier", "Caissier"),
                    ("infirmier", "Infirmier"),
                    ("medecin", "Medecin"),
                    ("laborantin", "Laborantin"),
                    ("pharmacien", "Pharmacien"),
                    ("comptable", "Comptable"),
                    ("directeur", "Directeur"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="personnel",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("licencie", "Licencie"),
                    ("retraite", "Retraite"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
    ]
