# Generated by Django 4.2.7 on 2025-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gestion_hospitaliere",
            "0003_personnel_adresse_personnel_date_embauche_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
