# Generated by Django 4.2.7 on 2025-12-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_hospitaliere", "0004_alter_personnel_date_naissance"),
    ]

    operations = [
        migrations.AddField(
            model_name="chambre",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chambres",
                to="gestion_hospitaliere.service",
                verbose_name="Service",
            ),
        ),
    ]
