# Generated by Django 4.2.7 on 2025-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_hospitaliere", "0005_chambre_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="poste",
            field=models.CharField(
                choices=[
                    ("receptioniste", "Receptioniste"),
                    ("caissier", "Caissier"),
                    ("infirmier", "Infirmier"),
                    ("medecin", "Medecin"),
                    ("laborantin", "Laborantin"),
                    ("pharmacien", "Pharmacien"),
                    ("comptable", "Comptable"),
                    ("comptable_matiere", "Comptable Matiere"),
                    ("directeur", "Directeur"),
                ],
                max_length=20,
            ),
        ),
    ]
