# Generated by Django 4.2.7 on 2025-12-14 17:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gestion_hospitaliere", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(blank=True, max_length=100)),
                ("date_naissance", models.DateField()),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numero de telephone doit contenir exactement 9 chiffres et commencer par 6.",
                                regex="^6\\d{8}$",
                            )
                        ],
                    ),
                ),
                ("nom_proche", models.CharField(max_length=100)),
                (
                    "contact_proche",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numero de telephone doit contenir exactement 9 chiffres et commencer par 6.",
                                regex="^6\\d{8}$",
                            )
                        ],
                    ),
                ),
                ("matricule", models.CharField(blank=True, max_length=10, unique=True)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients_enregistres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-date_inscription"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_examen", models.CharField(max_length=200)),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions_examens",
                        to="gestion_hospitaliere.medecin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Examen",
                "verbose_name_plural": "Prescriptions Examens",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("service_courant", models.CharField(max_length=100)),
                ("personnel_responsable", models.CharField(max_length=20)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en attente", "En attente"),
                            ("en cours", "En cours"),
                            ("terminee", "Terminee"),
                        ],
                        default="en cours",
                        max_length=20,
                    ),
                ),
                (
                    "situation_patient",
                    models.CharField(
                        choices=[("en attente", "En attente"), ("recu", "Recu")],
                        default="en attente",
                        max_length=20,
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="suivi_patient.patient",
                    ),
                ),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions_ouvertes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-debut"],
            },
        ),
        migrations.CreateModel(
            name="ResultatExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultat", models.TextField()),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats_examens",
                        to="gestion_hospitaliere.medecin",
                    ),
                ),
                (
                    "id_prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="suivi_patient.prescriptionexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultat Examen",
                "verbose_name_plural": "Resultats Examens",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rendez_vous",
                        to="gestion_hospitaliere.medecin",
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rendez_vous",
                        to="suivi_patient.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date_heure"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liste_medicaments", models.TextField()),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions_medicaments",
                        to="gestion_hospitaliere.medecin",
                    ),
                ),
                (
                    "id_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions_medicaments",
                        to="suivi_patient.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Medicament",
                "verbose_name_plural": "Prescriptions Medicaments",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.AddField(
            model_name="prescriptionexamen",
            name="id_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions_examens",
                to="suivi_patient.session",
            ),
        ),
        migrations.CreateModel(
            name="ObservationMedicale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation", models.TextField()),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations_medicales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations_medicales",
                        to="suivi_patient.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation Medicale",
                "verbose_name_plural": "Observations Medicales",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="Hospitalisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debut", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("en cours", "En cours"), ("terminee", "Terminee")],
                        default="en cours",
                        max_length=20,
                    ),
                ),
                (
                    "id_chambre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospitalisations",
                        to="gestion_hospitaliere.chambre",
                    ),
                ),
                (
                    "id_medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospitalisations",
                        to="gestion_hospitaliere.medecin",
                    ),
                ),
                (
                    "id_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalisations",
                        to="suivi_patient.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalisation",
                "verbose_name_plural": "Hospitalisations",
                "ordering": ["-debut"],
            },
        ),
    ]
