# Generated by Django 4.2.7 on 2025-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("effectue", "Effectué"),
                    ("annule", "Annulé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
