# Generated by Django 4.2.7 on 2025-12-19 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0002_add_statut_to_rendezvous"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierPatient",
            fields=[
                (
                    "id_patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="dossier_medical",
                        serialize=False,
                        to="suivi_patient.patient",
                    ),
                ),
                (
                    "groupe_sanguin",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "facteur_rhesus",
                    models.CharField(
                        blank=True,
                        choices=[("+", "Positif"), ("-", "Negatif")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "poids",
                    models.FloatField(
                        blank=True,
                        help_text="Poids en kg",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "taille",
                    models.FloatField(
                        blank=True,
                        help_text="Taille en metres",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("antecedents", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Dossier Patient",
                "verbose_name_plural": "Dossiers Patients",
            },
        ),
    ]
