# Generated by Django 4.2.7 on 2025-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0003_dossierpatient"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendezvous",
            name="motif",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motif de consultation"
            ),
        ),
    ]
