# Generated by Django 4.2.7 on 2025-12-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0004_rendezvous_motif"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionmedicament",
            name="state",
            field=models.CharField(
                choices=[("en attente", "En attente"), ("effectuee", "Effectuée")],
                default="en attente",
                max_length=20,
                verbose_name="État",
            ),
        ),
    ]
