# Generated by Django 4.2.7 on 2026-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0005_prescriptionmedicament_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="derniere_action",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="personnel_responsable",
            field=models.CharField(
                choices=[
                    ("infirmier", "Infirmier"),
                    ("medecin", "Medecin"),
                    ("laborantin", "Laborantin"),
                    ("receptioniste", "Receptioniste"),
                ],
                default="infirmier",
                max_length=20,
            ),
        ),
    ]
