# Generated by Django 4.2.7 on 2025-12-18 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quittance",
            fields=[
                (
                    "idQuittance",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant de la quittance",
                    ),
                ),
                (
                    "numero_quittance",
                    models.CharField(
                        help_text="Numéro unique de la quittance",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de quittance",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        help_text="Date et heure du paiement",
                        verbose_name="Date de paiement",
                    ),
                ),
                (
                    "Montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant payé (en FCFA)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "Motif",
                    models.TextField(
                        help_text="Motif ou description du paiement",
                        verbose_name="Motif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quittance",
                "verbose_name_plural": "Quittances",
                "db_table": "comptabilite_financiere_quittance",
                "ordering": ["-date_paiement"],
                "indexes": [
                    models.Index(
                        fields=["-date_paiement"], name="comptabilit_date_pa_709e80_idx"
                    ),
                    models.Index(
                        fields=["numero_quittance"],
                        name="comptabilit_numero__32fa61_idx",
                    ),
                ],
            },
        ),
    ]
