# Generated by Django 4.2.7 on 2025-12-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suivi_patient", "0004_rendezvous_motif"),
        ("comptabilite_financiere", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quittance",
            name="id_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session associée à cette quittance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quittances",
                to="suivi_patient.session",
                verbose_name="Session",
            ),
        ),
    ]
