# Generated by Django 4.2.7 on 2025-12-23 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("suivi_patient", "0005_prescriptionmedicament_state"),
        ("comptabilite_financiere", "0002_quittance_id_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "numero_cheque",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numéro du chèque",
                    ),
                ),
                (
                    "date_emission",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date et heure d'émission du chèque (automatique)",
                        verbose_name="Date d'émission",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant du chèque (en FCFA)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "date_encaissement",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure d'encaissement du chèque",
                        null=True,
                        verbose_name="Date d'encaissement",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient associé à ce chèque",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheques",
                        to="suivi_patient.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chèque",
                "verbose_name_plural": "Chèques",
                "db_table": "comptabilite_financiere_cheque",
                "ordering": ["-date_emission"],
                "indexes": [
                    models.Index(
                        fields=["-date_emission"], name="comptabilit_date_em_07f261_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="comptabilit_patient_74cd9d_idx"
                    ),
                ],
            },
        ),
    ]
