# Generated by Django 4.2.7 on 2025-12-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_hospitaliere", "0004_alter_personnel_date_naissance"),
        ("comptabilite_financiere", "0003_add_cheque_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestationDeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_comptable",
                    models.IntegerField(
                        help_text="Code comptable de la prestation",
                        verbose_name="Code Comptable",
                    ),
                ),
                (
                    "service_rendu",
                    models.ForeignKey(
                        help_text="Service associé à cette prestation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_service",
                        to="gestion_hospitaliere.service",
                        verbose_name="Service Rendu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation de Service",
                "verbose_name_plural": "Prestations de Service",
                "db_table": "comptabilite_financiere_prestation_de_service",
                "ordering": ["code_comptable"],
                "indexes": [
                    models.Index(
                        fields=["code_comptable"], name="comptabilit_code_co_b875d6_idx"
                    ),
                    models.Index(
                        fields=["service_rendu"], name="comptabilit_service_e548db_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="prestationdeservice",
            constraint=models.UniqueConstraint(
                fields=("code_comptable", "service_rendu"),
                name="unique_prestation_service",
            ),
        ),
    ]
