# Generated by Django 4.2.7 on 2025-12-26 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comptabilite_financiere", "0004_prestationdeservice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quittance",
            name="caissier",
            field=models.ForeignKey(
                blank=True,
                help_text="Caissier ayant émis la quittance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quittances_emises",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Caissier",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="compte_comptable_id",
            field=models.IntegerField(
                blank=True,
                db_column="compte_comptable_id",
                help_text="ID du compte comptable associé",
                null=True,
                verbose_name="Compte comptable ID",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="date_affectation_compte",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'affectation à un compte comptable",
                null=True,
                verbose_name="Date d'affectation compte",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="id_comptable_affectation",
            field=models.ForeignKey(
                blank=True,
                help_text="Comptable ayant affecté la quittance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quittances_affectees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comptable d'affectation",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("carte", "Carte bancaire"),
                    ("mobile_money", "Mobile Money"),
                    ("virement", "Virement"),
                    ("cheque", "Chèque"),
                    ("autre", "Autre"),
                ],
                default="especes",
                help_text="Mode de paiement utilisé",
                max_length=50,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="piece_recette_id",
            field=models.IntegerField(
                blank=True,
                db_column="piece_recette_id",
                help_text="ID de la pièce de recette associée",
                null=True,
                verbose_name="Pièce de recette ID",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="type_recette",
            field=models.CharField(
                choices=[
                    ("consultation", "Consultation"),
                    ("hospitalisation", "Hospitalisation"),
                    ("pharmacie", "Pharmacie"),
                    ("laboratoire", "Laboratoire"),
                    ("imagerie", "Imagerie"),
                    ("soins", "Soins"),
                    ("autre", "Autre"),
                ],
                default="soins",
                help_text="Type de recette",
                max_length=50,
                verbose_name="Type de recette",
            ),
        ),
        migrations.AddField(
            model_name="quittance",
            name="validee",
            field=models.BooleanField(
                default=False,
                help_text="Indique si la quittance a été validée par le comptable",
                verbose_name="Validée",
            ),
        ),
    ]
