# Generated by Django 4.2.7 on 2025-12-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "comptabilite_financiere",
            "0005_quittance_caissier_quittance_compte_comptable_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_compte",
                    models.CharField(
                        help_text="Numéro du compte selon le plan OHADA (ex: 706100)",
                        max_length=10,
                        unique=True,
                        verbose_name="Numéro de compte",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Nom descriptif du compte",
                        max_length=200,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        choices=[
                            ("1", "Classe 1 - Capitaux"),
                            ("2", "Classe 2 - Immobilisations"),
                            ("3", "Classe 3 - Stocks"),
                            ("4", "Classe 4 - Tiers"),
                            ("5", "Classe 5 - Trésorerie"),
                            ("6", "Classe 6 - Charges"),
                            ("7", "Classe 7 - Produits"),
                        ],
                        help_text="Classe du compte (1-7)",
                        max_length=1,
                        verbose_name="Classe",
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("produit", "Produit"),
                            ("charge", "Charge"),
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("tresorerie", "Trésorerie"),
                        ],
                        help_text="Type de compte (produit, charge, actif, passif, trésorerie)",
                        max_length=20,
                        verbose_name="Type de compte",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description détaillée du compte",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le compte est actif et utilisable",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "compte_parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte parent dans la hiérarchie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_comptes",
                        to="comptabilite_financiere.comptecomptable",
                        verbose_name="Compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte Comptable",
                "verbose_name_plural": "Comptes Comptables",
                "db_table": "comptabilite_financiere_comptecomptable",
                "ordering": ["numero_compte"],
            },
        ),
    ]
