# Generated by Django 4.2.7 on 2025-12-26 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comptabilite_financiere", "0006_add_compte_comptable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("JC", "Journal de Caisse"),
                            ("JB", "Journal de Banque"),
                            ("JMM", "Journal de Mobile Money"),
                            ("JOD", "Journal des Opérations Diverses"),
                        ],
                        help_text="Code unique du journal (JC, JB, JMM, JOD)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code du journal",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Nom complet du journal",
                        max_length=100,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description du journal",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le journal est actif",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "compte_contrepartie",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte utilisé par défaut pour ce journal (ex: 571 pour Caisse)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journaux_associes",
                        to="comptabilite_financiere.comptecomptable",
                        verbose_name="Compte de contrepartie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journaux",
                "db_table": "comptabilite_financiere_journal",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ecriture",
                    models.CharField(
                        help_text="Numéro unique de l'écriture (ex: EC-2025-00001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro d'écriture",
                    ),
                ),
                (
                    "date_ecriture",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date comptable de l'écriture",
                        verbose_name="Date de l'écriture",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Description de l'écriture",
                        max_length=255,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "piece_justificative",
                    models.CharField(
                        blank=True,
                        help_text="Référence de la pièce justificative",
                        max_length=100,
                        null=True,
                        verbose_name="Pièce justificative",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("validee", "Validée"),
                            ("annulee", "Annulée"),
                        ],
                        default="validee",
                        help_text="Statut de l'écriture",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "comptable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comptable ayant créé l'écriture",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comptable",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        help_text="Journal dans lequel l'écriture est enregistrée",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="comptabilite_financiere.journal",
                        verbose_name="Journal",
                    ),
                ),
                (
                    "quittance",
                    models.OneToOneField(
                        blank=True,
                        help_text="Quittance à l'origine de cette écriture",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecriture_comptable",
                        to="comptabilite_financiere.quittance",
                        verbose_name="Quittance source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "db_table": "comptabilite_financiere_ecriture",
                "ordering": ["-date_ecriture", "-numero_ecriture"],
            },
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        help_text="Description de la ligne",
                        max_length=255,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "montant_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant au débit",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Débit",
                    ),
                ),
                (
                    "montant_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant au crédit",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordre d'affichage de la ligne",
                        verbose_name="Ordre",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        help_text="Compte comptable mouvementé",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="comptabilite_financiere.comptecomptable",
                        verbose_name="Compte",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        help_text="Écriture parente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite_financiere.ecriturecomptable",
                        verbose_name="Écriture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "db_table": "comptabilite_financiere_ligne_ecriture",
                "ordering": ["ecriture", "ordre"],
                "indexes": [
                    models.Index(
                        fields=["compte"], name="comptabilit_compte__4caffd_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(
                fields=["-date_ecriture"], name="comptabilit_date_ec_678953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(
                fields=["journal"], name="comptabilit_journal_277825_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(
                fields=["numero_ecriture"], name="comptabilit_numero__a51c67_idx"
            ),
        ),
    ]
