# Generated by Django 4.2.7 on 2025-12-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_financiere", "0007_add_ecritures_comptables"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="nom_banque",
            field=models.CharField(
                default="",
                help_text="Nom de la banque émettrice du chèque",
                max_length=100,
                verbose_name="Nom de la banque",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="nom_titulaire",
            field=models.CharField(
                default="",
                help_text="Nom du titulaire du compte",
                max_length=200,
                verbose_name="Nom du titulaire",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="numero_cheque_externe",
            field=models.CharField(
                default="",
                help_text="Numéro inscrit sur le chèque",
                max_length=50,
                verbose_name="Numéro du chèque",
            ),
        ),
        migrations.AddField(
            model_name="cheque",
            name="quittance",
            field=models.ForeignKey(
                blank=True,
                help_text="Quittance associée à ce chèque",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cheques",
                to="comptabilite_financiere.quittance",
                verbose_name="Quittance",
            ),
        ),
        migrations.AlterField(
            model_name="cheque",
            name="numero_cheque",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID interne"
            ),
        ),
    ]
