# Generated by Django 4.2.7 on 2025-12-27 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("comptabilite_financiere", "0008_add_cheque_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirementBancaire",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "banque_emettrice",
                    models.CharField(
                        help_text="Nom de la banque d'où provient le virement",
                        max_length=100,
                        verbose_name="Banque émettrice",
                    ),
                ),
                (
                    "reference_virement",
                    models.CharField(
                        help_text="Référence ou motif du virement",
                        max_length=100,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "date_virement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du virement",
                    ),
                ),
                (
                    "compte_source",
                    models.CharField(
                        blank=True,
                        help_text="Numéro du compte débité",
                        max_length=50,
                        null=True,
                        verbose_name="Compte source (optionnel)",
                    ),
                ),
                (
                    "quittance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virement_bancaire",
                        to="comptabilite_financiere.quittance",
                        verbose_name="Quittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virement Bancaire",
                "verbose_name_plural": "Virements Bancaires",
                "db_table": "comptabilite_financiere_virement",
            },
        ),
        migrations.CreateModel(
            name="PaiementMobile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_payant",
                    models.CharField(
                        help_text="Numéro de téléphone qui a effectué le paiement",
                        max_length=20,
                        verbose_name="Numéro du payant",
                    ),
                ),
                (
                    "operateur",
                    models.CharField(
                        choices=[
                            ("orange", "Orange Money"),
                            ("mtn", "MTN Mobile Money"),
                            ("autre", "Autre"),
                        ],
                        default="orange",
                        max_length=20,
                        verbose_name="Opérateur",
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        help_text="Référence de la transaction mobile money",
                        max_length=100,
                        verbose_name="ID Transaction",
                    ),
                ),
                (
                    "quittance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiement_mobile",
                        to="comptabilite_financiere.quittance",
                        verbose_name="Quittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Mobile",
                "verbose_name_plural": "Paiements Mobiles",
                "db_table": "comptabilite_financiere_paiement_mobile",
            },
        ),
        migrations.CreateModel(
            name="PaiementCarte",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_carte_masque",
                    models.CharField(
                        help_text="Les 4 derniers chiffres de la carte (ex: **** 1234)",
                        max_length=20,
                        verbose_name="Numéro de carte (masqué)",
                    ),
                ),
                (
                    "reference_transaction",
                    models.CharField(
                        help_text="Référence de la transaction TPE/En ligne",
                        max_length=100,
                        verbose_name="Réf. Transaction",
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant du terminal de paiement (optionnel)",
                        max_length=50,
                        null=True,
                        verbose_name="ID Terminal",
                    ),
                ),
                (
                    "quittance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiement_carte",
                        to="comptabilite_financiere.quittance",
                        verbose_name="Quittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Carte",
                "verbose_name_plural": "Paiements Carte",
                "db_table": "comptabilite_financiere_paiement_carte",
            },
        ),
    ]
